FROM python:3.12-slim


RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /workspace


COPY requirements.txt /tmp/requirements.txt


RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r /tmp/requirements.txt


ENV DEEPFACE_HOME=/models
RUN mkdir -p /models

CMD ["bash"]
